# Generated by Django 3.2.17 on 2023-05-03 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Name Tasks')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Completed')),
                ('desc', models.CharField(max_length=500, verbose_name='description')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date and time creation')),
                ('date_end', models.DateTimeField(auto_now=True, verbose_name='Date and time closed')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'quest',
                'verbose_name_plural': 'questions',
            },
        ),
    ]
